### ISSUE TITLE
Backtrack interval is extremely diffucult to adjust with Unexpected keyboard

### ISSUE THREAD

**Issue by JacksonChen666** [kylecorry31/Trail-Sense#1807] opened 2023-06-11 20:25 UTC
Version 4.18.0

When trying to set the backtrack interval with the [Unexpected Keyboard](https://github.com/Julow/Unexpected-Keyboard), the cursor is invisible (well it always is) and the cursor is basically at the hours side so input is basically impossible.

Although it is quite unusable in general, even being buggy with the Android Keyboard.

https://github.com/kylecorry31/Trail-Sense/assets/50755746/f4ab98ed-3c1b-4826-8932-b991ff584be0

**Comment by kylecorry31** [comment] 2023-06-11 21:06
@JacksonChen666 I'm sorry you are having issues with Trail Sense. Oddly enough, I can't reproduce this issue on my Pixel 5A (stock) or emulator (stock) - but I can on my phone that runs GrapheneOS. Are you using a custom ROM as well?

The intended behavior is that it works like the timer apps on most phones - when I press a number key, it always adds to the right and pressing the back key removes the rightmost number.

**Comment by kylecorry31** [comment] 2023-06-11 21:34
@JacksonChen666 thanks, I plan on pushing the new release of Trail Sense later this week, and I'll include the fix for this.

**Closed** 2023-06-12 20:39 UTC
Labels: bug, ux, p2
