### ISSUE TITLE
Crash when editing a note

### ISSUE THREAD

**Issue by OmlineEditor** [kylecorry31/Trail-Sense#1129] opened 2022-01-10 15:58 UTC
Trail Sense: 3.1.0
Android SDK: 28
Device: Xiaomi lavender (Redmi Note 7)
Fragment: FragmentToolNotesCreate
Diagnostics: LocationOverridden, PowerSavingMode, BatteryUsageRestricted, BarometerUnavailable, GPSUnavailable, CameraNoPermission

Message: 

java.lang.NullPointerException
	at com.kylecorry.trail_sense.tools.notes.ui.FragmentToolNotesCreate$loadEditingNote$1$2.q(:2)
	at com.kylecorry.trail_sense.tools.notes.ui.FragmentToolNotesCreate$loadEditingNote$1$2.i(:2)
	at l3.d.D(Unknown Source:6)
	at w4.AlertExtensionsKt.N(:1)
	at com.kylecorry.trail_sense.tools.notes.ui.FragmentToolNotesCreate$loadEditingNote$1.q(:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.l(:3)
	at dc.f.a(:2)
	at w4.AlertExtensionsKt.w(:1)
	at bc.a.c0(:6)
	at w4.AlertExtensionsKt.s(:3)
	at com.kylecorry.andromeda.fragments.AndromedaFragment.C0(:1)
	at com.kylecorry.trail_sense.tools.notes.ui.FragmentToolNotesCreate.M(:3)
	at androidx.fragment.app.d0.e(:1)
	at androidx.fragment.app.d0.k(:8)
	at androidx.fragment.app.FragmentManager.E(:8)
	at androidx.fragment.app.FragmentManager.Z(Unknown Source:94)
	at androidx.fragment.app.FragmentManager.C(:4)
	at androidx.fragment.app.FragmentManager$g.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)

**Comment by kylecorry31** [comment] 2022-01-10 19:30
Thanks for reporting this - I'm going to put some extra checks in place to avoid a crash. Does this happen consistently for you? (on my phone, I'm unable to reproduce the issue - but I know what it can be caused by)

**Comment by OmlineEditor** [comment] 2022-01-10 20:51
It happens spontaneously, I can't repeat it

**Comment by kylecorry31** [comment] 2022-01-10 22:53
Thank you for the details - I'll have this fixed in the next release (some point during the week / weekend most likely)

**Closed** 2022-01-11 22:07 UTC
Labels: bug, notes
