### ISSUE TITLE
How does one record a bike trip?

### ISSUE THREAD

**Issue by gatopeich** [kylecorry31/Trail-Sense#1584] opened 2022-11-30 14:43 UTC
I want to record a bike trip as I ride, with route, altitude, timings, etc.
How can do?

**Comment by kylecorry31** [comment] 2022-11-30 15:06
Hi, you can use the Backtrack feature in Trail Sense to record a path.

To do this, you can do the following:

1. Open the Paths tool
2. On the bottom, you'll see a bar for Backtrack. Below "Backtrack", it will display how frequently it will run - tap the frequency to change it if needed.
3. On the bottom Backtrack bar, click the start button on the right, and a new path should be created and will update in the background.
4. Once your trip is completed, re-open paths and click the same start button to stop Backtrack.

Trail Sense may ask permission to be exempt from battery optimization - this will ensure Backtrack runs at the frequency you want. If you choose to allow the exemption, follow its instructions or see how to do it for your device here: https://dontkillmyapp.com/

Let me know if that helps.

**Comment by gatopeich** [comment] 2022-12-01 07:15
Thanks, I tried that a couple times but only got 1 point in the path.
I am using Android 11 on Fairphone 3

**Comment by kylecorry31** [comment] 2022-12-01 11:15
Hi, can you provide the following information:

1. Does Trail Sense have any errors or warnings on the Diagnostics tool (Trail Sense Settings > Diagnostics)? If so, please let me know what they are.
2. What frequency do you have Backtrack set to, and how long did you try to record the path for?

**Comment by kylecorry31** [comment] 2022-12-04 12:33
I'm making a change in the next release that should improve the reliability when backtrack is set to less than 15 minutes, but I was unable to reproduce the issue on my end, so I'm not sure if it will fix it for you once released.

**Comment by kylecorry31** [comment] 2022-12-10 11:31
I'm going to close this, as I think the change I made may fix this for you in the next release (4.10.0). If my assumption of you having backtrack set to less than 15 minutes was incorrect, please let me know.

**Closed by kylecorry31** 2022-12-10 11:31 UTC
Labels: user-education

**Comment by gatopeich** [comment] 2022-12-10 12:59
Thanks  I'll try and let u know if no luck.
